name: Latest blog post workflow
on:
  schedule:
    # Runs every night at 10pm
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.ryangraham.ca/feed.xml"